import Bai1 from './Bai1';
import Lap1 from './Lap1';
import Bai2 from './Bai2';
import Lap2 from './Lap2';
import Bai3 from './Bai3';
import Bai4 from './Bai4';
import Selecbox from './Selecbox';
import Camera from './Camera';
import Test from './Test';
import Lap_2_1 from './Lap2_1';
export {Bai1, Lap1, Bai2, Lap2, Bai3, Bai4, Selecbox, Camera, Test, Lap_2_1};
